### ISSUE TITLE
invalid repository type docker

### ISSUE THREAD

**Issue by steve-walker-sas** [sassoftware/sas-container-recipes#10]
Hi.  Is this message expected?   Was attempting to mirror the SAS repository as directed:

**_**_skipping docker/v2/va-100-x64_redhat_linux_7-docker due to invalid repository type docker_**_**

Entire command:

[cloud-user@viya-container ~]$ ./mirrormgr mirror --deployment-data /home/cloud-user/SAS_Viya_deployment_data.zip --platform x64-redhat-linux-7 --latest

Mirroring 1/2 docker/v2/va-100-x64_redhat_linux_7-docker
**_skipping docker/v2/va-100-x64_redhat_linux_7-docker due to invalid repository type docker_**
Mirroring 2/2 sasmd/shipped/va/100/va-100-x64_redhat_linux_7-dockersasmd
 8.77 KiB / 8.77 KiB [===============================================================================================================================================================] 100.00% 64.77 KiB/s 0s
Done

**Comment by g8sman** [comment]
Would have to ask around but if you were able to mirror the rest of the content then it should be fine.

**Comment by Collinux** [comment]
@steve-walker-sas is this still an issue?

**Comment by hornpolish** [comment]
this was not an expected message.  we havent had further reports of same so considering it closed at this time.

**Comment by boemska-nik** [comment]
I know it's old and closed but for anyone else hitting this, this issue appears to be related to `--platform x64-redhat-linux-7` not being a supported mirrormgr flag. 

As per the [docs](https://documentation.sas.com/?docsetId=dplydagent0phy0lax&docsetTarget=p1ilrw734naazfn119i2rqik91r0.htm&docsetVersion=2.3&locale=en), the flag `x64-redhat-linux-6` covers all supported versions of RHEL:

![image](https://user-images.githubusercontent.com/11962123/56658073-90f86600-6691-11e9-9c76-fcccc50b56b0.png)
