### ISSUE TITLE
Error:  Could not create base image

### ISSUE THREAD

**Issue by steve-walker-sas** [sassoftware/sas-container-recipes#11]
Tried a single machine image build, and got the following error.  Checked the .log, no help.

[cloud-user@viya-container sas-container-recipes]$ sudo ./build.sh --type single --zip /home/cloud-user/SAS_Viya_deployment_data.zip --addons "addons/auth-demo"

mkdir: created directory ‘/home/cloud-user/sas-container-recipes/logs’
‘/home/cloud-user/sas-container-recipes/build_sas_container.log’ -> ‘/home/cloud-user/sas-container-recipes/logs/build_sas_container_20181212122140.log’

==============
Variable check
==============

  Deployment Type                 = single
  BASEIMAGE                       = centos
  BASETAG                         = latest
  Mirror URL                      =
  Validate Mirror URL             = true
  Platform                        = redhat
  Deployment Data Zip             = /home/cloud-user/SAS_Viya_deployment_data.zip
  Addons                          =  addons/auth-demo
  Docker registry URL             =
  Docker registry namespace       =
  Validate Docker registry URL    = true
  HTTP Ingress endpoint           =
  Tag SAS will apply              = 18.11.0-20181212122140-e5ee16e

[INFO]  : Bypassing validation of mirror URL:

[INFO]  : Copying /home/cloud-user/SAS_Viya_deployment_data.zip to viya-programming/viya-single-container
‘/home/cloud-user/SAS_Viya_deployment_data.zip’ -> ‘viya-programming/viya-single-container/SAS_Viya_deployment_data.zip’

/home/cloud-user/sas-container-recipes/viya-programming/viya-single-container /home/cloud-user/sas-container-recipes

[INFO]  : Building the base image

+ docker build --file Dockerfile --label sas.recipe.version=18.11.0 --label sas.layer.viya-single-container=true --build-arg BASEIMAGE=centos --build-arg BASETAG=latest --build-arg PLATFORM=redhat . --tag viya-single-container
Sending build context to Docker daemon 83.97 kB
Step 1/25 : ARG BASEIMAGE=centos
Please provide a source image with `from` prior to commit
+ n_docker_build_rc=1
+ set +x

[ERROR] : Could not create base image

**Comment by g8sman** [comment]
What version of Docker are you running?

**Comment by hornpolish** [comment]
its happened to me before that /var/lib/docker is on a volume that is too small.  what does "df -h /var/lib/docker" say?  you'll need 10/15GB free

docker isnt great about diagnosing this.  you may find some hints in /var/lib/messages (our journalctl docker)

**Comment by g8sman** [comment]
That is an unsupported version of Docker. Please review the [supported versions](https://success.docker.com/article/maintenance-lifecycle). To install a more recent version, please see our [wiki](https://github.com/sassoftware/sas-container-recipes/wiki/The-Basics#where-can-i-find-information-about-installing-docker-on-centos). Closing ticket. Please reopen if a new version of Docker doesn't do the trick.

**Comment by steve-walker-sas** [comment]
Should I infer that RHEL docker is not supported  at all?  That's what I installed, and according to the yum install log, that docker build was compiled on Dec 6, which led me to believe it was up to date.

**Comment by g8sman** [comment]
That is not what is being inferred. What is being stated is that the version of Docker you are running is not supported by Docker. You will need to go to the Docker site to see how to install a supported version. Please review third party documentation to make sure it is being installed correctly. Installing from base level repositories is not guaranteed to give you the latest software so it is wise to make double check and make sure that you have a version that is supported.
