### ISSUE TITLE
Document links in Home.md are wrong

### ISSUE THREAD

**Issue by burgerzs** [sassoftware/sas-container-recipes#15]
Links at the beginning of the page like Introduction, System requirements, etc are resulting 404. It seems to me that ".md" is missing from the end of the links.

**Comment by g8sman** [comment]
Hi @burgerzs, if you are clicking on https://github.com/sassoftware/sas-container-recipes/blob/master/docs/wiki/Home.md, you are correct that will not work. We are currently maintaining the documentation with the code base but the doc is the source of the [Wiki](https://github.com/sassoftware/sas-container-recipes/wiki) site. If you use the Wiki, the links will work. We will provide a better explanation in sas-container-recipes/docs/ as to the reason for the wiki folder.
