### ISSUE TITLE
doshell and dostatus

### ISSUE THREAD

**Issue by egoienola** [sassoftware/sas-container-recipes#2]
Hi @hornpolish,
I've noticed that doshell and dostatus have a minor typo.

They both reference `allinone_sasawb_1` instead of `all-in-one_sasawb_1`

**Comment by hornpolish** [comment]
Hi @egoienola -- good catch;  on my linux box i was using docker-compose version 1.8 and it doesn't add the dashes.  I upgraded it to the latest 1.22, and now it generates the dashes into the names as you observe.   I will change the two scripts to use a generated container name with dashes.
