### ISSUE TITLE
invalid group ID 'docker' when building on Docker for Windows

### ISSUE THREAD

**Issue by Pulpanj** [sassoftware/sas-container-recipes#21]
I am trying to build sas-viya image using Docker on Windows 10. 
Build step started from GIT bash
$ ./build.sh --zip ../SAS_Viya_deployment_data.zip --addons "addons/auth-sssd" --type single

ends with groupadd: invalid group ID 'docker'
----end of log----
rm -r $WORK/b132/
Removing intermediate container d6e3bd563cec
 ---> 84c21dc8dc75
Step 6/19 : RUN groupadd --gid ${DOCKER_GID} docker
 ---> Running in 2145b18bd300
groupadd: invalid group ID 'docker'
The command '/bin/sh -c groupadd --gid ${DOCKER_GID} docker' returned a non-zero code: 3
----end of log----

Any idea? Any experience with sasviya image on Windows docker ?
Regards 
Jaroslav Pulpan

**Comment by alanzablocki** [comment]
I believe this is not supported. See page 6, Chapter 2 of the SAS Viya 3.4 for containers deployment guide. Docker host must be a Linux machine, physical or VM. I recommend you get a Centos 7 VM Guest on Windows 10 host and go from there.

**Comment by Pulpanj** [comment]
I dig into the issue and realized that it depends on flavor of bash (for Windows) you are using. Basically build scripts are ready just for Linux.
I had hardcoded build.sh into Windows bat file and successfully build docker container  that runs on Windows (including Jupyter). Happy camper now.
