### ISSUE TITLE
Modifying Dockerfile with custom addons

### ISSUE THREAD

**Issue by alanzablocki** [sassoftware/sas-container-recipes#24]
**Describe the bug**
I am wondering if after building an image with auth-demo and ide-jupyter-python3, running the same build but with a modification to Dockerfile in addons/ide-jupyter-python3/Dockerfile, will pick up on the fact that I have added R and Rstudio server installation:

RUN yum install epel-release \
&& yum update

RUN yum install -y R libcurl-devel cairo-devel \ 
&& yum clean all 

RUN wget https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.2.1335-x86_64.rpm \ 
 && yum install -y --nogpgcheck rstudio-server-rhel-1.2.1335-x86_64.rpm \ 
 && rm -f rstudio-server-rhel-1.2.1335-x86_64.rpm

Will the build.sh pick this change in Dockerfile up or should I start a new addon folder, called addons/ide-jupyter-python3-R-RStudio? 

Could we have R and RStudio added to the addons?

**Comment by Collinux** [comment]
@alanzablocki we currently don't have plans to support RStudio but feel free to add some RUN layers to that file and give it a try! `build.sh` will pick up lines that are added or removed from `addons/ide-jupyter-python3/Dockerfile`.

**Comment by alanzablocki** [comment]
Thanks @Collinux. I tried changing the Dockerfile and the changes were picked up on a second run of the ide-jupyter-python3 build, so that worked nicely.
