### ISSUE TITLE
Unclear instruction on mirror repository

### ISSUE THREAD

**Issue by rickyzhang82** [sassoftware/sas-container-recipes#8]
As a first time Viya user, it is unclear to me how and where I can get mirror repository URL as described in the [README doc here](https://github.com/sassoftware/sas-container-recipes#use-buildsh-to-build-the-images).

This is a roadblock to me. I'd expect some more technical details. For example, request an internal order to acquire deployment data from SAS. Also, we'd better provide an pre-built container that run mirror manager inside.

**Comment by g8sman** [comment]
@rickyzhang82, more information is on the [Wiki page](https://github.com/sassoftware/sas-container-recipes/wiki/The-Basics#why-do-i-need-a-local-mirror-repository). There is a broken link in the [prerequisite ](https://github.com/sassoftware/sas-container-recipes#sas-software)section that takes you to that page. We will get that fixed.

**Comment by g8sman** [comment]
@rickyzhang82, you are correct that an end user coming here has an order. That is stated in the prerequiste section. 

> SAS Viya 3.4 software: a SAS Viya 3.4 on Linux order and the SAS_Viya_deployment_data.zip from the Software Order Email (SOE) are required.

I guess we can look at providing an image that has mirror manager in it but I don't think that is the hard part. You need storage to store the content for the mirror and then you need to have a http endpoint to serve up the mirror. Do you want a mirror image that does this all on behalf of the user? Or do you want an image that just has mirror manager in it so the user doesn't have to curl, unpack and run mirrormgr?

**Comment by g8sman** [comment]
The link on the readme has been fixed to point to the correct location on the Wiki. I am going to close out this issue. More feedback is welcomed on what is desired from a MirrorMgr Docker image. It could be wrapped up into its own image, but one would still need to know the options to pass and identify where to store the mirror (Docker Volume, Kubernetes volume, physical storage, etc). Cheers!
