### ISSUE TITLE
Proxy issue with ide-jupyter-python3 addon

### ISSUE THREAD

**Issue by githje** [sassoftware/sas-container-recipes#9]
There's probably something missing with the documentation for the "ide-jupyter-python3" addon. A plain "docker build" (as the readme suggests) will not copy the httpd proxy.conf into the new container, which means that Jupyter can't be reached from the outside. 

I see that there's a Dockerfile_http which does just that.  It's probably meant to be run as a separate step before or after the main build? However it seems to make assumptions concerning the internal hostname so it didn't work for me.

I used this as a simple workaround for the issue:

`echo "COPY proxy.conf /etc/httpd/conf.d/jpy3_proxy.conf" >> Dockerfile`

(followed by the usual docker build command).

**Comment by g8sman** [comment]
You are correct that we need to update the documentation if you are trying to add on the layer outside of using the root level `build.sh` script. You would need to run the `docker build` process twice using each of the Docker files that are available. The logic looks like it is not as forgiving as it needs to be in the Dockerfile_http. We will probably need to introduce a new build argument to indicate if we are supporting a single or multiple container to make this work. Assuming that you are trying to create a single container, you could do something like:

```
docker build --file Dockerfile --build-arg BASEIMAGE=viya-single-container --build-arg BASETAG=latest  . --tag viya-single-container:jpy3
docker build --file Dockerfile --build-arg BASEIMAGE=viya-single-container --build-arg BASETAG=jpy3  . --tag svc-ide-jupyter-python3
```

If you are using the multi-container flow, this proxy.conf file needs to be added to the httpproxy Docker image.

**Comment by githje** [comment]
Thanks @g8sman! Yes, I'm not using the build.sh script - should have mentioned that before. I think there's a typo in your explanation. The first build should be using Dockerfile_http, right? 

This works for me:

```
docker build --file Dockerfile_http --build-arg BASEIMAGE=viya-single-container --build-arg BASETAG=latest  . --tag viya-single-container:jpy3
docker build --file Dockerfile --build-arg BASEIMAGE=viya-single-container --build-arg BASETAG=jpy3  . --tag svc-ide-jupyter-python3
```

Then I headed over to addons/auth-demo for example and did

```
docker build --file Dockerfile --build-arg BASEIMAGE=svc-ide-jupyter-python3 --build-arg BASETAG=latest  . --tag svc-auth-demo
```
 Thanks for the explanation, I'm fine with that.
